### ISSUE TITLE
Salus crashing due to lack of `cargo-audit`

### ISSUE THREAD

**Issue by Piccirello** [federacy/scan-action#8] opened 2023-04-03 18:49 UTC
Linking for visibility: https://github.com/coinbase/salus/issues/828

**Comment by quentinlesceller** [comment] 2023-04-19 15:09
Any update on this? 

@Piccirello sounds like you are mainly running Go code. You can add this line to your Github Actions file workflow (or `sales-config.yaml`) to fix the missing `cargo-audit` binary issue:
```
        with:
          active_scanners: "\n  - Gosec\n  - PatternSearch\n  - RepoNotEmpty\n  - Semgrep\n  - GoOSV\n  - GoVersionScanner\n  - GoPackageScanner\n  - ReportGoDep\n  - Trufflehog"
 ```

The same scanners will run. But it will not start the cargo-audit one in the background.

**Comment by Piccirello** [comment] 2023-04-19 21:19
@quentinlesceller thank you!

**Comment by joshuaostrom-cb** [comment] 2023-04-21 12:44
Salus Maintainer here.  Thanks for the work around.  The root cause is the custom entry point:

The custom entry point is the issue:

export PYTHONPATH="$PYTHONPATH:/root/.local/lib/python3.7/site-packages"

https://github.com/federacy/scan-action/blob/master/entrypoint.sh#L4

The correct path should be
 /root/.local/lib/python3.9/site-packages
 as we've upgraded the image to use pyhton 3.9 👍

**Comment by quentinlesceller** [comment] 2023-04-21 18:34
Thanks @joshua-ostrom. I've created a PR with your changes. If it is not merged after a while I might fork the repo and maintain it.

**Closed as completed** 2023-05-10 23:06 UTC
